### PR TITLE
New, more material icon, based on Dumitri's

### PR DESCRIPTION
**Pull request by tenebr050**
Trying to comply more with the [material design icon guidelines](www.google.com/design/spec/style/icons.html#icons-product-icons)

### CODE REVIEW

**Comment by testica** [comment]
Nice icon, but try to follow [Material color palette](http://www.google.com/design/spec/style/color.html#color-color-palette), for black (` #212121`) and red (`#C62828` , `#D32F2F`, or `#B71C1C`)

**Comment by tenebr050** [comment]
@testica You have a point there. I tried using material red 600 on a `#212121` background. How does [this](https://github.com/tenebr050/turbo-editor/commit/499a6739ecaf40bae8718922750c5efa92efb30f) look?

**Comment by testica** [comment]
@tenebr050 That's it!

**Comment by tenebr050** [comment]
All right! @vmihalachi Please have a look.

**Comment by tenebr050** [comment]
And here's the 512x512 web icon:
web_hi_res_512

**Comment by vmihalachi** [comment]
I really appreciate your efforts and I am thankful for that but I have already designed a new material icon. :)

**Comment by tenebr050** [comment]
Ah well, never mind. :)

**Pull request closed without merging**
